[package]
name = "hecto"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
unicode-segmentation = "1.11.0"
unicode-width = "0.1.12"
chrono = "0.4.41"
log = "0.4.27"
fern = "0.7.1"
